# Generated by Django 4.0.2 on 2022-02-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_product_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
