# Generated by Django 4.0.2 on 2022-02-27 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_product_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 14, 43, 38, 71849, tzinfo=utc)),
        ),
    ]
